# Generated by Django 4.2.5 on 2023-09-12 17:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('data', models.BinaryField()),
                ('file_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'FILE',
            },
        ),
        migrations.CreateModel(
            name='MonetaryPenalty',
            fields=[
                ('monetary_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('premiseId', models.CharField(blank=True, max_length=255, null=True)),
                ('startDate', models.CharField(blank=True, max_length=255, null=True)),
                ('endDate', models.CharField(blank=True, max_length=255, null=True)),
                ('penaltyAuthority', models.CharField(blank=True, max_length=255, null=True)),
                ('penaltyCurrency', models.CharField(blank=True, max_length=255, null=True)),
                ('penaltyAmount', models.CharField(blank=True, max_length=255, null=True)),
                ('penaltyCase', models.CharField(blank=True, max_length=255, null=True)),
                ('penaltyAppeal', models.CharField(blank=True, max_length=255, null=True)),
                ('penaltyAppealReason', models.CharField(blank=True, max_length=255, null=True)),
                ('penaltyAppealFile', models.CharField(blank=True, max_length=255, null=True)),
                ('settlementAuthority', models.CharField(blank=True, max_length=255, null=True)),
                ('settlementCurrency', models.CharField(blank=True, max_length=255, null=True)),
                ('settlementAmount', models.CharField(blank=True, max_length=255, null=True)),
                ('settlementCase', models.CharField(blank=True, max_length=255, null=True)),
                ('settlementAppeal', models.CharField(blank=True, max_length=255, null=True)),
                ('settlementAppealReason', models.CharField(blank=True, max_length=255, null=True)),
                ('settlementAppealFile', models.CharField(blank=True, max_length=255, null=True)),
                ('compoundFeeAuthority', models.CharField(blank=True, max_length=255, null=True)),
                ('compoundFeeCurrency', models.CharField(blank=True, max_length=255, null=True)),
                ('compoundFeeAmount', models.CharField(blank=True, max_length=255, null=True)),
                ('compoundFeeCase', models.CharField(blank=True, max_length=255, null=True)),
                ('compoundFeeAppeal', models.CharField(blank=True, max_length=255, null=True)),
                ('compoundAppealReason', models.CharField(blank=True, max_length=255, null=True)),
                ('compoundAppealFile', models.CharField(blank=True, max_length=255, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('createdOn', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'MONETARY_PENALTY',
            },
        ),
    ]
